### PR TITLE
fix: report node when loc not found

### LINKED ISSUE #687: Node must be provided when reporting error if location is not provided
If I run `bun run lint` - I get error
```
ESLint: 8.57.1
AssertionError [ERR_ASSERTION]: Node must be provided when reporting error if location is not provided
```

Here is the reproducible repository https://github.com/FDiskas/remix-dev

### PR DESCRIPTION
**Pull request by ntnyq**
This PR fixes #687.

### CODE REVIEW

File: eslint-plugin-prettier.js [hunk 1]
```diff
@@ -160,11 +161,11 @@ const eslintPluginPrettier = {
         const source = sourceCode.text;
 
         return {
-          Program() {
+          Program(node) {
             if (!prettierFormat) {
               // Prettier is expensive to load, so only load it if needed.
-              prettierFormat = require('synckit').createSyncFn(
-                require.resolve('./worker'),
+              prettierFormat = /** @type {PrettierFormat} */ (
```
Comment (JounQin) [inline eslint-plugin-prettier.js:167]: Is the casting here required? It should work fine without it, shouldn't?

**Comment by JounQin** [comment]
@ntnyq I can't edit the PR directly because of missing permission, so please help to add a changeset, or enable [Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

File: eslint-plugin-prettier.js (hunk 1 above)
Comment (ntnyq) [reply eslint-plugin-prettier.js:167]: Will get an TS error `Type '(...args: any[]) => unknown' is not assignable to type '(source: string, options: Options, fileInfoOptions: FileInfoOptions) => string'.
  Type 'unknown' is not assignable to type 'string'.` if no type casting.

**Review by JounQin — APPROVED** [review]

**Comment by JounQin** [comment]
Thanks for your contribution first! Can you add a test case for it?

**Comment by ntnyq** [comment]
> Thanks for your contribution first! Can you add a test case for it?

Yes, I'll add the test case after I finish my lunch.

**Comment by ntnyq** [comment]
Sorry I failed to add a test case for this.

The original issue has mixed usage of esm and cjs syntax in `prettier.config.cjs` that causes the error.

I can't reproduce it in test even if I tried to add an integrated test.

**Comment by JounQin** [comment]
@ntnyq See [`d6b90c1` (#700)](https://github.com/prettier/eslint-plugin-prettier/pull/700/commits/d6b90c15120d264305c90d00013c7bc15204b4be) for adding a failing test case commit.

Thanks for your work!
